### ISSUE TITLE
您好~想给您关于FurryDownloader的建议

### ISSUE THREAD

**Issue by ee092884** [recallfuture/FurryDownloader#2]
您好~~您开发的软件个人觉得很赞
有缓存纪录可以跳过重复档案
不过这样一个一个贴上FA的ID或昵称 操作上有些繁琐
不知道可不可以新增一个列表来下载呢
把添加进去的例如作者链接 、ID、名字贴进列表后一起全部批量下载
这样之后在开启软件时就不必再重贴一次ID或昵称
直接就按开始下载 就有点像另外一边开发的tumblr下载软件
tumblr下载软件链接：https://github.com/TumblThreeApp/TumblThree/releases

这样之后开启软件就可以直接按开始 就可以直接快速下载新图片
还有一点就是文件名称 因为有些创作者 ID跟他使用的昵称是不同的 有些在别的平台上
例如推特 假如ID不同 至少如果昵称相同的话还可以找到文件在哪 方便归类
就例如说 "eudemonsstreet (EUDEMONS_STREET)"
eudemonsstreet 是链接上面的ID  
EUDEMONS_STREET 是昵称
除了大小写不同之外 还有个"_"之类的符号
这样有时搜寻时就会找不到

eudemonsstreet (EUDEMONS_STREET)  是我归档时习惯
"链接ID (昵称)" 这样去命名文件 给您作参考一下

**Comment by recallfuture** [comment]
#### 感谢给出这么详尽的建议！！

邮件我也收到了，统一在这里回复吧

其实在上一次更新加入多线程下载的时候，我就有考虑过把每个文件的下载进度都在列表里展示出来，但限于现在使用的http库实在不给力，想做出那种效果得改好多，而且界面同样需要大改，再想了想这软件估计没几个人用，也就作罢

####  但是！得到了这么珍贵的建议！还有什么理由放弃！

由于当前项目本意是轻量级的下载器，且有一些遗留问题不太好解决，所以我决定重写这个项目，会开一个新的repository(新坑)

作者列表和下载队列必然要加进去，至于昵称和id的关系，实际上id就是昵称去掉下划线并且全变成小写，所以改为用昵称来做为作者文件夹名字应该就可以了

开好新repository之后我会在这里说一声，这段时间如果还有什么建议也尽管提吧！
