### ISSUE TITLE
关于FurryDownloader的建议

### ISSUE THREAD

**Issue by gitgusky** [recallfuture/FurryDownloader#3]
你好，试用了FurryDownloader后
界面简洁易懂，速度也相当不错
但几个建议希望能够参考
1.自定下载图片数量
目前很多furaffinity的下载器几乎都是gallery全部下载
但除非是新关注的画师，不然是不需要全部下载的
只需要画师新更新的图，自己以前都​​已经保存下来了
自定下载图片数量，我觉得这功能真的很重要
但大部分下载器都没这个功能
后来在删重复的图花了很多时间
只抓需要的部分对减少furaffinity伺服器的负担也比较好
例如：
在高级选项新增到第几页第几张停止
如果都不填入数值则默认全部下载

2.下载时的资讯显示
使用过后觉得讯息很混乱
全部都是下载完成
我看过资讯后发现同一张图会出现两次下载完成
但实际上应该要显示开始下载与下载完成
这部份可以修正
还有每个讯息后面都有已经过XXX秒
我觉可以拿掉，会让讯息很杂
只需要保留最后的总时间
最后的总时间秒数显示也有错误
会出现共X小时X分钟XX秒秒
'秒'字会重复

给您作参考

**Comment by recallfuture** [comment]
感谢提出建议，抱歉没注意到邮件提醒，回复晚了（也太晚了吧！）。

1. 自定下载图片数量
这个在加入多线程下载之前是存在的，加入后发现无法精确的在到达某个数量时停下，于是乎去掉了。如果不介意这里的误差，我就把它再加回来。

2. 下载时的资讯显示
这个确实是个问题，而且文本框能力有限，没法突出显示某些字（比如错误信息），重要的信息就埋在那些普通日志里面了。

精简日志也很好说，成功的项目只要留下“第n页第n张下载完成”，失败的项目再尽量多显示相关信息。

**Comment by gitgusky** [comment]
如果是用頁來計算呢？就是只下載到第n頁的圖片這樣也不需要精確數量。

另外發現了一個新的問題，新版下載資訊顯示有問題，當下載完新的圖後是顯示"下載完成"，這是正確的，但是當同畫師再次下載時已下載完的圖還是顯示"下載完成"而不是"已存在"，重開還是一樣。


夙 <notifications@github.com> 於 2020年1月6日 週一 下午7:10 寫道：

**Comment by gitgusky** [comment]
關於顯示錯誤問題，可能是因為新版把gallery的圖改存到畫師名（資料夾）下而不是原來的gallery資料夾裡，當把新下載的圖移到原來gallery裡後，再次下載顯示就正常了

古樂天 <guskytest@gmail.com> 於 2020年2月15日 週六 下午2:57 寫道：

**Comment by recallfuture** [comment]
已经发布5.3，更新页数和最大下载量的设定，请查收
